name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=dilipsuthar74129@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "remote.msi"
         "remote.msi"
         "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AeaYSHC3y583v_U-INPi_ihwlHZVgb-GTg79X7fw-6QcDW_nl_rgLgdQDUgS4J5WYmZ_Aw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME%
         

      - name: Time Counter
        run: python time.py

